# Generated by Django 4.2.16 on 2026-01-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='donation_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='donation_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
